# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 547e8733f5a5e381b91a34dbbf15b398b1224a840c08a61337d5ecd92a29c6966845e411c351374882bbca2dc2423c33a6f5e6e4675c71d0da28631ddc410a84

test:
  secret_key_base: 5c0a3b24e7013a2ba5a1a32daa73075d6953aebb802fa7eb077b8919f9310a45974556d5fc9fe868f658b9cff73ed4e48bf582714eb8571108eab89b756d9979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
